backend:
  name: github
  repo: contactjknewstoday-a11y/jk-news-today
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "News Articles"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Kashmir","India","World","Sports","Technology","Business"]}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Content", name: "body", widget: "markdown"}
